//go:build apicheck

package apicheck

// commands covers every command that reaches Stripe. Adding a command without
// adding it here means its requests go unvalidated, so keep this exhaustive.
func commands() [][]string {
	return [][]string{
		{"balance", "get"},
		{"accounts", "self"},
		{"accounts", "list"},
		{"accounts", "get", "acct_mock_connected"},
		{"accounts", "persons", "list", "acct_mock_connected", "--relationship", "owner"},
		{"accounts", "persons", "get", "acct_mock_connected", "person_mock_v1_rep"},
		{"accounts", "capabilities", "acct_mock_connected"},
		{"accounts", "external-accounts", "acct_mock_connected", "--object", "bank_account"},
		{"customers", "list", "--email", "buyer@example.com"},
		{"customers", "get", "cus_mock_123"},
		{"customers", "search", "--query", "email:'buyer@example.com'"},
		{"events", "list", "--type", "charge.failed", "--created-gte", "1700000000"},
		{"events", "get", "evt_mock_charge_failed"},
		{"charges", "list", "--customer", "cus_mock_123"},
		{"charges", "get", "ch_mock_succeeded", "--expand", "payment_intent"},
		{"charges", "search", "--query", "amount>100"},
		{"payment-intents", "list", "--customer", "cus_mock_123"},
		{"payment-intents", "get", "pi_mock_succeeded"},
		{"payment-methods", "list", "--customer", "cus_mock_123", "--type", "card"},
		{"payment-methods", "get", "pm_mock_card"},
		{"setup-intents", "list", "--customer", "cus_mock_123"},
		{"invoices", "list", "--customer", "cus_mock_123", "--status", "open"},
		{"invoices", "get", "in_mock_paid"},
		{"invoices", "line-items", "in_mock_paid"},
		{"invoices", "search", "--query", "number:'MOCK-0001'"},
		{"invoices", "preview", "--subscription", "sub_mock_active"},
		{"subscriptions", "list", "--customer", "cus_mock_123", "--status", "all"},
		{"subscriptions", "get", "sub_mock_active"},
		{"subscriptions", "items", "sub_mock_active"},
		{"subscriptions", "invoices", "sub_mock_active", "--status", "open"},
		{"disputes", "list", "--charge", "ch_mock_succeeded"},
		{"refunds", "list", "--payment-intent", "pi_mock_succeeded"},
		{"transfers", "list", "--destination", "acct_mock_connected", "--transfer-group", "order_123"},
		{"payouts", "list", "--status", "failed"},
		{"balance-transactions", "list", "--type", "charge", "--payout", "po_mock_failed"},
		{"application-fees", "list", "--charge", "ch_mock_succeeded"},
		{"application-fees", "get", "fee_mock_123"},
		{"balance-transactions", "get", "txn_mock_succeeded"},
		{"checkout-sessions", "get", "cs_mock_paid"},
		{"disputes", "get", "dp_mock_needs_response"},
		{"early-fraud-warnings", "get", "issfr_mock_1"},
		{"payment-intents", "search", "--query", "status:'succeeded'"},
		{"payment-links", "get", "plink_mock_1"},
		{"payouts", "get", "po_mock_failed"},
		{"prices", "get", "price_mock_basic"},
		{"prices", "search", "--query", "product:'prod_mock_basic'"},
		{"products", "get", "prod_mock_basic"},
		{"products", "search", "--query", "name:'Basic'"},
		{"refunds", "get", "re_mock_pending"},
		{"setup-intents", "get", "seti_mock_1"},
		{"subscriptions", "search", "--query", "status:'active'"},
		{"transfers", "get", "tr_mock_failed"},
		{"products", "list", "--active", "true"},
		{"prices", "list", "--product", "prod_mock_basic", "--type", "recurring"},
		{"payment-links", "list", "--active", "true"},
		{"early-fraud-warnings", "list", "--charge", "ch_mock_succeeded"},
		{"checkout-sessions", "list", "--customer", "cus_mock_123"},
		{"checkout-sessions", "line-items", "cs_mock_paid"},
		{"investigate", "resolve", "ch_mock_succeeded"},
		{"investigate", "customer-context", "--customer", "cus_mock_123"},
		{"investigate", "customer-card-payment", "--customer", "cus_mock_123", "--last4", "4242"},
		{"investigate", "incoming-payment", "pi_mock_failed"},
		{"investigate", "invoice-payment", "in_mock_paid"},
		{"investigate", "invoice-collection", "cus_mock_123"},
		// cus_mock_456 owns the past-due invoices, so this reaches the
		// PaymentIntent and charge lookups behind a failed collection.
		{"investigate", "invoice-collection", "cus_mock_456"},
		{"investigate", "invoice-metadata", "in_mock_paid"},
		{"investigate", "subscription-renewal", "--subscription", "sub_mock_active"},
		{"investigate", "subscription-items", "--subscription", "sub_mock_active"},
		{"investigate", "subscription-amount-change", "--subscription", "sub_mock_active"},
		{"investigate", "entitlement", "--subscription", "sub_mock_active"},
		{"investigate", "collection-risk", "--days", "30"},
		{"investigate", "subscription-cancel-risk", "--days", "30"},
		{"investigate", "checkout-session", "cs_mock_paid"},
		{"investigate", "payment-method-readiness", "cus_mock_123"},
		{"investigate", "setup", "cus_mock_123"},
		{"investigate", "timeline", "cus_mock_123"},
		{"investigate", "dispute-response", "dp_mock_open"},
		{"investigate", "dispute-impact", "ch_mock_succeeded"},
		{"investigate", "fraud-review", "ch_mock_succeeded"},
		{"investigate", "refund", "ch_mock_succeeded"},
		{"investigate", "refund-recovery", "ch_mock_succeeded"},
		{"investigate", "ledger", "ch_mock_succeeded"},
		{"investigate", "payout-failure", "po_mock_failed"},
		{"investigate", "outgoing-payment", "tr_mock_failed"},
		{"investigate", "webhook-event", "evt_mock_charge_failed"},
		{"investigate", "webhook-delivery", "evt_mock_charge_failed"},
		{"investigate", "account-health", "acct_mock_connected"},
		{"investigate", "account-health", "acct_mock_v2_restricted"},
		{"investigate", "account-events", "acct_mock_v2_restricted"},
		{"investigate", "connect-readiness", "--limit", "3"},
		{"investigate", "duplicate-charge", "--customer", "cus_mock_123", "--last4", "4242"},
		{"investigate", "statement-descriptor", "--descriptor", "FUREVER", "--customer", "cus_mock_123"},
		{"investigate", "action-required", "--customer", "cus_mock_123"},
		{"investigate", "refund-settlement", "re_mock_settled"},
		{"investigate", "invoice-total", "in_mock_tax_mismatch"},
		{"accounts-v2", "list"},
		{"accounts-v2", "get", "acct_mock_v2_restricted"},
		{"accounts-v2", "persons", "list", "acct_mock_v2_restricted"},
		{"accounts-v2", "payout-methods", "acct_mock_v2_recipient"},
		{"accounts-v2", "persons", "get", "acct_mock_v2_restricted", "person_mock_representative"},
		{"events-v2", "list", "--object-id", "acct_mock_v2_restricted"},
		{"events-v2", "get", "evt_test_mock_requirements_updated"},
	}
}
